Models/ExamResult.cs
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace University_Final_Project.Models
{
    public class ExamResult
    {
        [Key]
        public int  Exam_Id { get; set; }

        public string Student_FId { get; set; }
        public string subject_FId{ get; set; }
       
        public  int  semester { get; set; }
        public double Marks { get; set; }
        [NotMapped]
        public double gpa { get; set; }
        [NotMapped]
        public string Grade { get; set; }

        public Subject subject { get; set; }
        public Student student { get; set; }

    }
}

Models/Transcript.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace University_Final_Project.Models
{
    public class Transcript
    {
        public int semester { get; set; }

        public float GPA { get; set; }

        public float CGPA { get; set; }

        public int CrHrs { get; set; }
        public List<ExamResult> examResults { get; set; }
    }
}

Controllers/ExamResultsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDataReader;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using University_Final_Project.Models;
using System.ComponentModel;
using University_Final_Project.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using OfficeOpenXml;
using DocumentFormat.OpenXml.Spreadsheet;

namespace University_Final_Project.Controllers
{
    public class ExamResultsController : Controller
    {
        private readonly ExamContext _context;

        public IWebHostEnvironment Env;
        private readonly GradeCalculator gradeCalculator;
        
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SubjectRepository subjectRepository;
        private readonly IStudentRepository studentRepository;
        private readonly IExamResultRepository examResultRepository;

        public ExamResultsController(ExamContext context, IWebHostEnvironment env,
            GradeCalculator gradeCalculator, UserManager<ApplicationUser> userManager
            , SubjectRepository subjectRepository, IStudentRepository studentRepository,
            IExamResultRepository examResultRepository)
        {
            _context = context;
            Env = env;
            this.gradeCalculator = gradeCalculator;
         
            this.userManager = userManager;
            this.subjectRepository = subjectRepository;
            this.studentRepository = studentRepository;
            this.examResultRepository = examResultRepository;
        }

        // GET: ExamResults
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Index(string searchString,string ErrorMessage)
        {

            ViewBag.Error = ErrorMessage;

            var examResults = await _context.ExamResults.OrderBy(e => e.semester).ToListAsync();
            if (searchString != null)
            {
                 var results= await _context.ExamResults.Include(e=>e.student).Include(e=>e.subject)
                    .Where(e=>e.Student_FId==searchString)
                  .OrderBy(e => e.semester).ToListAsync();
               
            }
        

            examResults = gradeCalculator.calculateGpa(examResults);
            return View(examResults);




        }

        // GET: ExamResults/Details/5
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examResult = await _context.ExamResults
                .FirstOrDefaultAsync(m => m.Exam_Id== id);

         
            if (examResult == null)
            {
                return NotFound();
            }

            return View(examResult);
        }

        // GET: ExamResults/Create
        [Authorize(Roles = "Admin,Teacher")]
        public IActionResult Create()
        {
            ViewBag.List = new SelectList(_context.Subjects, "Subject_Id", "corse_title");
            return View();
        }

        // POST: ExamResults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Create(IFormFile file, ExamResult exam, int semester)
        {

            ViewBag.List = new SelectList(_context.Subjects, "Subject_Id", "corse_title");

              var result = string.Empty;
                string worksheetsName = "data";

                bool firstRowIsHeader = false;
                var format = new ExcelTextFormat();
                format.Delimiter = ',';
                format.TextQualifier = '"';

                var reader = new StreamReader(file.OpenReadStream()) ;
                ExcelPackage package = new ExcelPackage();

                    result = reader.ReadToEnd();
                    ExcelWorksheet worksheet =
                    package.Workbook.Worksheets.Add(worksheetsName);
                    worksheet.Cells["A1"].LoadFromText(result, format, OfficeOpenXml.Table.TableStyles.Medium27, firstRowIsHeader);



                int rowCount = worksheet.Dimension.End.Row;
                int colCount = worksheet.Dimension.End.Column;
                int col = 0;
                List<ExamResult> examresults = new List<ExamResult>();
                for (int row = 2; row <= rowCount; row++)
                {


                    col = 1;



                        var val1 = worksheet.Cells[row, col].Value;
                    ++col;
                        var val2 = worksheet.Cells[row, col].Value;
                 
                
                    if (val1 != null && val2 != null) {
                        examresults.Add(new ExamResult()
                        {

                            Student_FId = val1.ToString(),
                            Marks = (double)val2

                        });
                    }


                }


                foreach (var item in examresults)
                {
                    item.subject_FId = exam.subject_FId;
                    item.semester = semester;
                    _context.ExamResults.Add(item);
                    _context.SaveChanges();
                    ViewBag.Success = true;
                }
          
            return View();
        }



        // GET: ExamResults/Edit/5
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.list = new SelectList(_context.Subjects.ToList(), "Subject_Id", "corse_title");
            var examResult = await examResultRepository.FindExamResultAsync(id);
            if (examResult == null)
            {
                return NotFound();
            }
            return View(examResult);
        }

        // POST: ExamResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Edit(int id,  ExamResult examResult,int semester)
        {
            if (id != examResult.Exam_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    examResult.semester = semester;
                    _context.Update(examResult);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExamResultExists(examResult.Exam_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(examResult);
        }

        // GET: ExamResults/Delete/5
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examResult = await examResultRepository.FindExamResultAsync(id);
            if (examResult == null)
            {
                return NotFound();
            }

            return View(examResult);
        }

        // POST: ExamResults/Delete/5
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await examResultRepository.DeleteExamResultAsync(id);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> ViewTranscript(string filterString,string std_id)
        {
            ViewBag.std_id = User.Identity.Name;
            if (std_id == null)
            {
                std_id = User.Identity.Name;
            }
            TranscriptWithStudent transcriptWithStudent = new TranscriptWithStudent();
            List<Transcript> transcript = new List<Transcript>();
            var results = await _context.ExamResults.Where(e =>
                           e.Student_FId == std_id).AsNoTracking().OrderBy(e => e.semester).ToListAsync();
            var res = new List<ExamResult>();
            var semestercount = results.Max(a => a.semester);
            var semTosemRes = new List<ExamResult>();

            for (int i = 1; i <= semestercount; i++)
            {
                res = results.Where(e =>
                       e.semester == i).ToList();

                foreach (var item in res)
                {
                    item.subject = await subjectRepository.GetSubjectAsync(item.subject_FId);
                    semTosemRes.Add(item);
                }
                res = gradeCalculator.calculateGpa(res);
                var gpa = (float)gradeCalculator.calculateCgpa(res);
                var cgpa = (float)gradeCalculator.calculateCgpa(semTosemRes);
                var TCrHrs = gradeCalculator.TotalCrHrs(res);
                transcript.Add(new Transcript()
                {
                    examResults = res,
                    semester = i,
                    GPA = gpa,
                    CGPA = cgpa,
                    CrHrs = TCrHrs

                });

            }

Views/ExamResults/AdminViewTranscript.cshtml
@model University_Final_Project.Models.TranscriptWithStudent
@inject University_Final_Project.Repository.IStudentRepository studentRepository
@inject University_Final_Project.Repository.SubjectRepository subjectRepository

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />

<div id="tran">
    <Center>
        <h3 style="color:red">ACADEMIC TRANSCRIPT</h3>
        <h4>Department of @Model.student.degree.department.departmentName  </h4>
        <h5>Bachelor of @Model.student.degree.DegreeName</h5>
    </Center>


    <table class="table">


        <tr>
            <th></th>
            <td></td>
            <th>Reg No : </th>
            <td>@Model.student.Reg_Number</td>
            <td rowspan="3"><img src="~/images/uni-logo.png" /></td>
        </tr>
        <tr>
            <th>Name :</th>
            <td>@await studentRepository.GetFullNameAsync(Model.student.Roll_Number)</td>
            <th>Roll No :</th>
            <td>@Model.student.Roll_Number</td>
        </tr>
        <tr>
            <th>Father Name : </th>
            <td>@Model.student.Father_Name</td>
            <th>Session : </th>
            <td>@Model.student.Session_Start-@(Model.student.Session_Start+4)</td>
        </tr>

    </table>
    <div class="row">
        <div class="col-sm-6">
            <table class="table" border="2">
                <thead>
                    <tr>
                        <th scope="col">Code</th>
                        <th scope="col">Title</th>
                        <th scope="col">Cr Hrs</th>
                        <th scope="col">Marks</th>
                        <th scope="col">Grade</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="col-sm-6">
            <table class="table" border="1">
                <thead>
                    <tr>
                        <th scope="col">Code</th>
                        <th scope="col">Title</th>
                        <th scope="col">Cr Hrs</th>
                        <th scope="col">Marks</th>
                        <th scope="col">Grade</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>


    <div class="row">
        @{
        }
        @foreach (var item in Model.transcripts)
        {
            <div class="col-sm-6">
                <table class="table" style="height:400px">
                    <thead class="thead-light">
                        <tr>
                            <th colspan="5" class="text-center">Semester @item.semester</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var i in item.examResults)
                        {
                            <tr>
                                <td>@i.subject.Subject_Id</td>
                                <td>@i.subject.corse_title</td>
                                <td>@i.subject.credit_hours</td>
                                <td>@i.Marks</td>
                                <td>@i.Grade</td>
                            </tr>
                        }


                        <tr>
                            <td></td>
                            <td></td>
                            <th>Cr Hrs </th>
                            <td>@item.CrHrs</td>

                        </tr>
                        <tr>
                            <th>Semester GPA</th>
                            <td>@item.GPA</td>
                            <th>CGPA </th>
                            <td>@item.CGPA</td>

                        </tr>
                    </tbody>
                </table>


            </div>
        }


    </div>



</div>
<button class="btn btn-primary" onclick="printContent('tran')">Print</button>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/custom.js"></script>
}

Views/ExamResults/Create.cshtml
@model University_Final_Project.Models.ExamResult

@{
    ViewData["Title"] = "Create";
}


<hr />
@if (ViewBag.success!=null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
         Record added  succesfully!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container ">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label"><h4>Download Template File</h4></label>
                    <a asp-action="DownloadResultTemplate" class="btn btn-success form-control">Download Template</a><br />
                    <label class="control-label"><h4>Choose Result File</h4></label>
                    <input type="file" name="File" class="form-control" required data-val="true" data-val-required="The csv file is required."><br>
                    <span class="text-danger field-validation-valid" data-valmsg-for="File" data-valmsg-replace="true"></span><br>
                    <label class="control-label"><h4>Subject</h4></label>
                    <select asp-for="subject_FId" asp-items="ViewBag.list" class="form-control">
                    </select><br>
                    <label class="control-label"><h4>Semester</h4></label>
                    <select asp-for="semester" class="form-control">
                        <option value="1" name="semester">
                            1
                        </option>
                        <option value="2" name="semester">
                            2
                        </option>
                        <option value="3" name="semester">
                            3
                        </option>
                        <option value="4" name="semester">
                            4
                        </option>
                        <option value="5" name="semester">
                            5
                        </option>
                        <option value="6" name="semester">
                            6
                        </option>
                        <option value="7" name="semester">
                            7
                        </option>
                        <option value="8" name="semester">
                            8
                        </option>
                    </select>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />|
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>

            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ExamResults/Delete.cshtml
@model University_Final_Project.Models.ExamResult

@{
    ViewData["Title"] = "Delete";
}



<h3 style="color:red">Are you sure you want to delete this?</h3>
<div>
    <h4>ExamResult</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject_FId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject_FId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student_FId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student_FId)
        </dd>
     
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marks)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Exam_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index"class="btn btn-primary">Back to List</a>
    </form>
</div>

Views/ExamResults/Details.cshtml
@model University_Final_Project.Models.ExamResult
@inject University_Final_Project.Repository.SubjectRepository subjectRepository

@{
    ViewData["Title"] = "Details";
}



<div>
    <hr />
    <h3>Exam Result Details</h3>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Student ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.subject_FId)
        </dd>
        <dt class="col-sm-2">
           Subject
        </dt>
        <dd class="col-sm-10">
            @subjectRepository.getSubjectName(Model.subject_FId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.semester)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.semester)
        </dd>
        <dt class="col-sm-2">
            Marks 
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marks)
        </dd>
    
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Exam_Id" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

Views/ExamResults/Edit.cshtml
@model University_Final_Project.Models.ExamResult

@{
    ViewData["Title"] = "Edit";
}
<hr />
<h3>Edit Exam Result</h3>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="ExamResults" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Exam_Id" />
        
            <div class="form-group">
                <label class="control-label">Student ID</label>
                <input asp-for="Student_FId" class="form-control" />
                <span asp-validation-for="Student_FId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Subject</label>
                <select asp-for="subject_FId" asp-items="ViewBag.list"class="form-control" ></select>
            </div>
            <div class="form-group">
                <label class="control-label">Semester</label>
                <select asp-for="semester"class="form-control" >
                    <option value="1" name="semester">
                        1
                    </option>
                    <option value="2" name="semester">
                        2
                    </option>
                    <option value="3" name="semester">
                        3
                    </option>
                    <option value="4" name="semester">
                        4
                    </option>
                    <option value="5" name="semester">
                        5
                    </option>
                    <option value="6" name="semester">
                        6
                    </option>
                    <option value="7" name="semester">
                        7
                    </option>
                    <option value="8" name="semester">
                        8
                    </option>
                </select>
            </div>
           
            <div class="form-group">
                <label  class="control-label">Sessional Marks</label>
                <input asp-for="Marks" class="form-control" />
                <span asp-validation-for="Marks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />|
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ExamResults/Index.cshtml
@model IEnumerable<University_Final_Project.Models.ExamResult>

@inject University_Final_Project.Repository.SubjectRepository subjectRepository
@inject University_Final_Project.Repository.IStudentRepository studentRepository
@{
    ViewData["Title"] = "Index";
}






<div class="d-inline">
    <form asp-action="AdminViewTranscript" method="get">

        <div class="form-actions no-color form-inline">

            <p id="para">
                <a asp-action="Create" class="btn btn-primary ml-2">Create New</a>
                <a asp-action="Index" class="btn btn-secondary  ml-2">Back to Full List</a>
                <h5 class="ml-auto">ID of Student : </h5> <input type="text" name="std_id" class="ml-2" />
                <input type="submit" value="Transcript" class="btn btn-primary ml-2" />

            </p>
        </div>
    </form>


</div>



@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
    <hr>
}


<table class="table">
    <thead>
        <tr>
            <th>
                Subject
            </th>
            <th>
                Student ID
            </th>
            <th>
                Name
            </th>
            <th>
                Semester
            </th>

            <th>
                Marks
            </th>
            <th>GPA</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @subjectRepository.getSubjectName(item.subject_FId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student_FId)
                </td>
                <td>
                    @await studentRepository.GetFullNameAsync(item.Student_FId)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.semester)
                </td>

                <td>
                    @item.Marks
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gpa)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Exam_Id" class="btn btn-primary">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Exam_Id" class="btn btn-primary">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Exam_Id" class="btn btn-danger">Delete</a>

                </td>
            </tr>
        }
    </tbody>
</table>
<hr />

Views/ExamResults/Transcript.cshtml
@model ExamResult
@inject University_Final_Project.Repository.IStudentRepository studentRepository
@inject University_Final_Project.Repository.SubjectRepository subjectRepository

<table class="table">


    <tr>
        <th></th>
        <td></td>
        <th>Reg No : </th>
        <td>pujc-123-omn</td>
        <td rowspan="3"><img src="~/images/uni-logo.png" /></td>
    </tr>
    <tr>
        <th>Name :</th>
        <td>Zakir Islam</td>
        <th>Roll No :</th>
        <td>BSCS-F17-A-06</td>
    </tr>
    <tr>
        <th>Father Name : </th>
        <td>Muhammad Safdar</td>
        <th>Session : </th>
        <td>2017 - 2021</td>
    </tr>

</table>
<div class="row">
    <div class="col-sm-6">
        <table class="table" border="2">
            <thead >
                <tr>
                    <th scope="col">Code</th>
                    <th scope="col">Title</th>
                    <th scope="col">Cr Hrs</th>
                    <th scope="col">Marks</th>
                    <th scope="col">Grade</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="col-sm-6">
        <table class="table" border="1">
            <thead>
                <tr>
                    <th scope="col">Code</th>
                    <th scope="col">Title</th>
                    <th scope="col">Cr Hrs</th>
                    <th scope="col">Marks</th>
                    <th scope="col">Grade</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

    
<div class="row">
    @for (int i = 0; i < 8; i++)
    {
        <div class="col-sm-6">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th colspan="5" class="text-center">Semester</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td >1</td>
                        <td>Mark</td>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>mdo</td>
                    </tr>
                    <tr>
                        <td >2</td>
                        <td>Mark</td>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>fat</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Mark</td>
                        <td>Larry</td>
                        <td>the Bird</td>
                        <td>twitter</td>
                    </tr>
                    <tr>
                        <td><br></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <th>Cr Hrs : </th>
                        <td>12</td>

                    </tr>
                    <tr>
                        <td>Semester GPA :</td>
                        <td>3.90</td>
                        <th>CGPA : </th>
                        <td>3.90</td>

                    </tr>
                </tbody>
            </table>


        </div>
    }


</div>